"use client";
import { useMemo, useState } from "react";
import { questions } from "@/lib/questions";

export default function AdminQuestions() {
  const [query, setQuery] = useState(""), [length, setLength] = useState("all"), [showForm, setShowForm] = useState(false);
  const rows = useMemo(() => questions.filter((q) => (length === "all" || Array.from(q.answer).length === Number(length)) && (q.answer.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr")) || q.clue.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr")))), [query, length]);
  return <main className="mx-auto min-h-screen max-w-6xl px-5 py-8"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-teal-300">YÖNETİCİ PANELİ</p><h1 className="text-3xl font-black">Sorular</h1></div><button onClick={() => setShowForm(!showForm)} className="rounded-xl bg-amber-300 px-5 py-3 font-black text-slate-950">+ Yeni soru</button></header>
  {showForm && <form className="panel mt-6 grid gap-4 rounded-2xl p-5 md:grid-cols-2" onSubmit={(e) => e.preventDefault()}><input required placeholder="Cevap kelimesi" className="rounded-xl bg-slate-900 p-3"/><input placeholder="TDK üzerinden sorgula" className="rounded-xl bg-slate-900 p-3"/><textarea required placeholder="Dolaylı soru" className="rounded-xl bg-slate-900 p-3 md:col-span-2"/><select className="rounded-xl bg-slate-900 p-3"><option>Kolay</option><option>Orta</option><option>Zor</option></select><button className="rounded-xl bg-teal-300 p-3 font-black text-slate-950">Taslak kaydet</button></form>}
  <section className="panel mt-6 rounded-2xl p-5"><div className="flex gap-3"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Soru veya cevap ara" className="min-w-0 flex-1 rounded-xl bg-slate-900 p-3"/><select value={length} onChange={(e) => setLength(e.target.value)} className="rounded-xl bg-slate-900 p-3"><option value="all">Tüm uzunluklar</option>{[4,5,6,7,8,9,10].map((n) => <option key={n}>{n}</option>)}</select></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th className="p-3">Cevap</th><th className="p-3">Harf</th><th className="p-3">Dolaylı soru</th><th className="p-3">Durum</th></tr></thead><tbody>{rows.map((q) => <tr key={q.answer} className="border-t border-white/10"><td className="p-3 font-black text-amber-300">{q.answer}</td><td className="p-3">{Array.from(q.answer).length}</td><td className="p-3 text-slate-300">{q.clue}</td><td className="p-3 text-teal-300">Aktif</td></tr>)}</tbody></table></div></section></main>;
}
