"use client";

import { useEffect, useState } from "react";
import { SinglePlayerGame } from "@/components/SinglePlayerGame";
import { Leaderboard } from "@/components/Leaderboard";
import { MAX_LOBBY_PLAYERS, canStartLobby } from "@/lib/lobby";

type Screen = "home" | "single" | "join" | "lobby" | "multi" | "leaders";
type Player = { id: number; name: string; connected: boolean; host?: boolean };

function createCode() { const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; const bytes = crypto.getRandomValues(new Uint8Array(6)); return Array.from(bytes, (value) => alphabet[value % alphabet.length]).join(""); }

export default function Home() {
  const [screen, setScreen] = useState<Screen>("home");
  const [name, setName] = useState("");
  const [players, setPlayers] = useState<Player[]>([]);
  const [lobbyCode, setLobbyCode] = useState("");
  useEffect(() => { const saved = localStorage.getItem("kelime-oyunu-player") || ""; setName(saved); const code = new URLSearchParams(location.search).get("oda")?.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6); if (code?.length === 6) { setLobbyCode(code); setScreen("join"); } }, []);
  const remember = () => { const clean = name.trim().slice(0, 20); if (clean.length < 2) return false; localStorage.setItem("kelime-oyunu-player", clean); setName(clean); return true; };
  const open = (target: Screen) => { if (target === "leaders" || target === "join") return setScreen(target); if (!remember()) return; if (target === "lobby") { setLobbyCode(createCode()); setPlayers([{ id: Date.now(), name: name.trim(), connected: true, host: true }]); } setScreen(target); };
  if (screen === "single") return <main className="min-h-screen px-4 py-8"><SinglePlayerGame name={name} onFinish={() => setScreen("home")}/></main>;
  if (screen === "multi") return <main className="min-h-screen px-4 py-8"><SinglePlayerGame name={name} online questionSeed={`online:${lobbyCode}`} rivals={players.filter((p) => p.name !== name).map((p, i) => ({ name: p.name, score: 0, question: 1 + i % 2, connected: p.connected }))} onExit={() => setScreen("lobby")} onFinish={() => setScreen("home")}/></main>;
  if (screen === "leaders") return <main className="mx-auto min-h-screen max-w-3xl px-4 py-8"><button onClick={() => setScreen("home")} className="mb-5 text-sm text-teal-300">← Ana menü</button><Leaderboard/></main>;
  if (screen === "join") return <JoinRoom name={name} setName={setName} code={lobbyCode} setCode={setLobbyCode} onBack={() => setScreen("home")} onJoin={() => { if (!remember() || lobbyCode.length !== 6) return; setPlayers([{ id: 1, name: "Oda Yöneticisi", connected: true, host: true }, { id: Date.now(), name: name.trim(), connected: true }]); setScreen("lobby"); }}/>
  if (screen === "lobby") return <Lobby name={name} code={lobbyCode} players={players} setPlayers={setPlayers} onBack={() => setScreen("home")} onStart={() => setScreen("multi")}/>;
  return <main className="mx-auto flex min-h-screen max-w-6xl items-center px-5 py-10"><section className="grid w-full gap-10 lg:grid-cols-[1.1fr_.9fr]">
    <div className="py-5"><p className="brand-kicker mb-5 text-xs font-black uppercase tracking-[.2em]">Canlı Türkçe kelime yarışması</p><h1 className="brand-title text-7xl md:text-9xl">Kelime<br/><span>Oyunu</span></h1><p className="mt-8 max-w-xl text-lg font-semibold leading-relaxed text-slate-300">Tek başına rekor kır veya 2–5 kişilik lobide arkadaşlarına meydan oku.</p><div className="mt-9 max-w-lg"><label htmlFor="name" className="text-xs font-black uppercase tracking-widest">Oyuncu adın</label><input id="name" value={name} onChange={(e) => setName(e.target.value)} minLength={2} maxLength={20} placeholder="2–20 karakter" className="mt-2 w-full px-4 py-3 outline-none"/></div></div>
    <div className="panel grid gap-3 p-6 md:p-8"><Mode title="Tek Oyunculu" text="530 doğal sorudan seçilen 14 soruyla yarış." onClick={() => open("single")}/><Mode title="Lobi Oluştur" text="6 karakterli oda kodu ve davet linki oluştur." onClick={() => open("lobby")}/><Mode title="Lobiye Katıl" text="Oda koduyla veya davet linkiyle katıl." onClick={() => open("join")}/><button onClick={() => open("leaders")} className="mt-2 border border-white/10 py-3 font-bold text-slate-300">🏆 Lider Tablosu</button></div>
  </section></main>;
}

function Mode({ title, text, onClick }: { title: string; text: string; onClick: () => void }) { return <button onClick={onClick} className="mode-card p-5 pr-14 text-left"><span className="text-xl font-black uppercase">{title}</span><span className="mt-1 block text-sm text-slate-400">{text}</span></button>; }

function JoinRoom({ name, setName, code, setCode, onBack, onJoin }: { name: string; setName: (value: string) => void; code: string; setCode: (value: string) => void; onBack: () => void; onJoin: () => void }) { return <main className="mx-auto flex min-h-screen max-w-lg items-center px-4 py-8"><section className="panel w-full p-7"><button onClick={onBack} className="text-sm text-teal-300">← Ana menü</button><p className="brand-kicker mt-7 text-xs font-black uppercase">Online oda</p><h1 className="mt-4 text-3xl font-black">Lobiye Katıl</h1><label className="mt-6 block text-xs font-black uppercase tracking-widest">Oyuncu adın</label><input value={name} onChange={(e) => setName(e.target.value)} maxLength={20} className="mt-2 w-full px-4 py-3"/><label className="mt-5 block text-xs font-black uppercase tracking-widest">6 karakterli oda kodu</label><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6))} placeholder="ABC123" className="mt-2 w-full px-4 py-3 text-center text-2xl font-black tracking-[.3em]"/><button disabled={name.trim().length < 2 || code.length !== 6} onClick={onJoin} className="mt-6 w-full bg-amber-300 p-3 font-black disabled:opacity-40">ODAYA KATIL</button></section></main>; }

function Lobby({ name, code, players, setPlayers, onBack, onStart }: { name: string; code: string; players: Player[]; setPlayers: React.Dispatch<React.SetStateAction<Player[]>>; onBack: () => void; onStart: () => void }) {
  const ready = canStartLobby(players), invite = typeof window === "undefined" ? "" : `${location.origin}/?oda=${code}`;
  const addDemo = () => { if (players.length < MAX_LOBBY_PLAYERS) setPlayers((rows) => [...rows, { id: Date.now(), name: `Oyuncu ${rows.length + 1}`, connected: true }]); };
  const copy = () => navigator.clipboard.writeText(invite);
  const share = () => navigator.share ? navigator.share({ title: "Kelime Oyunu", text: `Oda kodu: ${code}`, url: invite }) : copy();
  return <main className="mx-auto min-h-screen max-w-4xl px-4 py-8"><button onClick={onBack} className="mb-5 text-sm text-teal-300">← Lobiden ayrıl</button><section className="panel p-6 md:p-9"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-slate-400">Online oda kodu</p><h1 className="mt-1 text-4xl font-black tracking-[.18em] text-amber-300">{code}</h1><p className="mt-2 text-sm text-slate-400">Kodu veya davet linkini arkadaşlarınla paylaş.</p><div className="mt-4 flex gap-2"><button onClick={copy} className="bg-[#eef3fc] px-4 py-2 text-sm font-black">LİNKİ KOPYALA</button><button onClick={share} className="bg-[#eef8f3] px-4 py-2 text-sm font-black">PAYLAŞ</button></div></div><b className="rounded-full bg-teal-400/15 px-4 py-2 text-teal-300">{players.length}/5 oyuncu</b></header><div className="mt-7 grid gap-6 md:grid-cols-[1fr_260px]"><div className="space-y-3">{players.map((player, index) => <div key={player.id} className="flex items-center gap-3 rounded-2xl border border-[#d8d0c1] bg-white p-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#eef8f3] font-black">{index + 1}</span><b className="flex-1">{player.name}</b>{player.host && <small className="rounded-full bg-[#fff7db] px-3 py-1 font-black text-amber-300">YÖNETİCİ</small>}<span className="h-2.5 w-2.5 rounded-full bg-green-600"/></div>)}{players.length < 5 && <button onClick={addDemo} className="w-full rounded-2xl border border-dashed border-[#b9ad99] p-3 text-sm text-slate-400">+ Yerel test oyuncusu</button>}</div><div className="rounded-2xl bg-[#eef3fc] p-5"><h2 className="font-black">Online yarışma</h2><p className="mt-2 text-sm text-slate-400">Herkes aynı anda 14 soruyu çözer; puanlar canlı görünür.</p><button onClick={onStart} disabled={!ready} className="mt-6 w-full bg-amber-300 p-3 font-black disabled:opacity-30">YARIŞMAYI BAŞLAT</button><p className="mt-2 text-center text-xs text-slate-500">En az 2 oyuncu gerekir.</p></div></div></section></main>;
}
