import type { PublicQuestion } from "./game";

type Pair = [string, string];
const pairs: Pair[] = [
  ["ABAJUR","Işığı yumuşatmak için lambanın çevresine geçirilen başlık."],
  ["ADRES","Bir yerin bulunmasını sağlayan mahalle, sokak ve numara bilgisi."],
  ["AHŞAP","Ağaçtan elde edilip eşya ve yapılarda kullanılan malzeme."],
  ["AKASYA","Salkım biçimli çiçekler açan, kimi türleri dikenli ağaç."],
  ["AKIŞKAN","Bulunduğu kabın biçimini alabilen sıvı veya gaz durumundaki madde."],
  ["ALBÜM","Fotoğraf ya da müzik eserlerinin bir araya getirildiği koleksiyon."],
  ["AMBALAJ","Bir ürünü koruyan ve satışa hazırlayan dış kaplama."],
  ["AMPUL","Elektrik enerjisini ışığa dönüştüren cam aydınlatma aracı."],
  ["ANTRENÖR","Bir sporcuyu teknik ve fiziksel olarak yarışmaya hazırlayan kişi."],
  ["ARŞİV","Belgelerin düzenli biçimde saklandığı yer veya bütün."],
  ["ASANSÖR","İnsanları ve yükleri katlar arasında taşıyan kabinli sistem."],
  ["ATLAS","Haritaların bir kitap biçiminde bir araya getirildiği eser."],
  ["AVİZE","Tavana asılan, genellikle birden çok ışık kaynağı bulunan süslü lamba."],
  ["BALKON","Bir yapının dışına taşan, korkulukla çevrili açık bölüm."],
  ["BAMBU","Boğumlu gövdesi hızla uzayan, dayanıklı tropikal bitki."],
  ["BARINAK","Canlıları hava koşullarından veya tehlikeden koruyan yer."],
  ["BAVUL","Yolculukta giysi ve eşyaların taşındığı kapaklı çanta."],
  ["BECERİKLİ","Elinden birçok iş gelen ve işini ustalıkla yapan."],
  ["BESLENME","Canlının yaşamını sürdürmek için gerekli maddeleri alma süreci."],
  ["BİLET","Bir yolculuk veya etkinliğe giriş hakkını gösteren belge."],
  ["BİNA","İnsanların yaşaması veya çalışması için yapılmış kapalı yapı."],
  ["BİTKİ","Toprağa bağlı yaşayan ve çoğunlukla fotosentez yapan canlı."],
  ["BOYUT","Bir cismin uzunluk, genişlik veya yükseklik ölçülerinden biri."],
  ["BUHAR","Bir sıvının ısı etkisiyle dönüştüğü gaz durumu."],
  ["BULVAR","Genellikle ağaçlı ve geniş olarak düzenlenmiş şehir yolu."],
  ["CETVEL","Düz çizgi çizmeye ve uzunluk ölçmeye yarayan araç."],
  ["CIVATA","Somunla birlikte parçaları birbirine bağlayan yivli metal çubuk."],
  ["ÇADIR","Direk ve kumaşla kurulan, taşınabilir geçici barınak."],
  ["ÇAKIL","Su veya aşınma etkisiyle yuvarlanmış küçük taş parçası."],
  ["ÇEKMECE","Dolap veya masa içinde ileri geri kayarak açılan göz."],
  ["ÇİMENTO","Su ve kumla karıştırıldığında sertleşen yapı bağlayıcısı."],
  ["ÇİZGİ","Bir noktanın hareketiyle oluştuğu düşünülen uzun ve ince iz."],
  ["ÇORAP","Ayağa giyilen, bilekten dize kadar uzanabilen örgü giysi."],
  ["DAMLA","Bir sıvının yüzey gerilimiyle aldığı küçük yuvarlak parça."],
  ["DEHLİZ","Bir yapının bölümlerini birbirine bağlayan dar ve uzun geçit."],
  ["DEMET","Çiçek veya benzeri ince uzun şeylerin bağlanmış bütünü."],
  ["DENKLEM","İki matematiksel ifadenin eşitliğini gösteren bağıntı."],
  ["DİREKSİYON","Bir taşıtın gideceği yönü değiştirmeye yarayan kumanda."],
  ["DOKUMA","İpliklerin birbirinin altından ve üstünden geçirilmesiyle oluşan yüzey."],
  ["DÜRÜST","Gerçeği saklamayan ve aldatmaya başvurmayan kişi."],
  ["ECZANE","İlaçların hazırlandığı veya reçeteyle satıldığı sağlık işletmesi."],
  ["EKRAN","Elektronik aygıtlarda görüntünün izlendiği yüzey."],
  ["ELDİVEN","Elleri soğuktan, kirden veya tehlikeden koruyan giysi."],
  ["FENER","Taşınabilir bir ışık kaynağı veya denizcilere yol gösteren kule."],
  ["FİDAN","Yeni yetişmekte olan genç ağaç."],
  ["FİLTRE","Bir karışımdaki istenmeyen parçaları ayıran süzme düzeneği."],
  ["FIRÇA","Boyama veya temizlemede kullanılan, kılları bir sapa tutturulmuş araç."],
  ["FİŞEK","Ateşli silahlarda kullanılan veya ışık gösterisi oluşturan düzenek."],
  ["FOSİL","Geçmiş çağlarda yaşamış bir canlının kayaçta korunmuş kalıntısı."],
  ["FREKANS","Belirli sürede tekrarlanan titreşim veya dalga sayısı."],
  ["GALERİ","Sanat eserlerinin sergilendiği salon veya yapının uzun geçidi."],
  ["GAZETE","Güncel olayları düzenli aralıklarla okura ulaştıran yayın."],
  ["GEZEGEN","Bir yıldızın çevresinde belirli yörüngede dolanan gök cismi."],
  ["GİŞE","Bilet veya para işlemlerinin küçük bir pencereden yapıldığı bölüm."],
  ["GÖLGE","Işığın bir cisim tarafından kesilmesiyle oluşan karanlık alan."],
  ["GÖMLEK","Üst bedene giyilen, yakalı ve çoğunlukla düğmeli giysi."],
  ["GÖZLÜK","Görmeyi düzeltmek veya gözleri korumak için takılan araç."],
  ["GÜBRE","Bitkinin gelişmesi için toprağa verilen besleyici madde."],
  ["GÜMRÜK","Ülkeye giren ve çıkan malların denetlendiği kurum veya yer."],
  ["HARİTA","Bir bölgenin yeryüzü özelliklerini ölçekli olarak gösteren çizim."],
  ["HASAT","Olgunlaşmış tarım ürünlerini toplama işi."],
  ["HAZİNE","Değerli eşya ve paraların saklandığı büyük birikim."],
  ["HEYKEL","Taş, metal veya başka malzemeden üç boyutlu yapılan sanat eseri."],
  ["HIRDAVAT","Onarım işlerinde kullanılan çivi, vida ve benzeri küçük araçlar."],
  ["HİDROJEN","Periyodik tablonun ilk sırasında bulunan en hafif element."],
  ["HOPARLÖR","Elektrik sinyallerini duyulabilir sese dönüştüren aygıt."],
  ["HORTUM","Sıvı veya gaz taşımaya yarayan esnek boru."],
  ["IZGARA","Yiyeceği ateş üzerinde pişirmeye yarayan aralıklı metal yüzey."],
  ["İKLİM","Bir bölgede uzun yıllar boyunca gözlenen hava koşulları bütünü."],
  ["İSKELE","Gemiye geçişi sağlayan yapı veya inşaatta kurulan geçici platform."],
  ["JENERATÖR","Mekanik enerjiyi elektrik enerjisine dönüştüren makine."],
  ["KABLO","Elektrik veya veri ileten, yalıtılmış tel demeti."],
  ["KALDIRIM","Yolun kenarında yayaların yürümesi için ayrılan yükseltilmiş bölüm."],
  ["KAMERA","Hareketli veya durağan görüntüyü kaydeden optik aygıt."],
  ["KAMPÜS","Bir eğitim kurumunun binalarını ve açık alanlarını kapsayan yerleşke."],
  ["KANO","Kürekle ilerletilen, dar ve hafif su taşıtı."],
  ["KARAVAN","İçinde yaşama donanımı bulunan, taşınabilir veya motorlu araç."],
  ["KASİYER","Bir işletmede ödeme alıp para işlemlerini yapan görevli."],
  ["KAVANOZ","Yiyecek saklamak için kullanılan geniş ağızlı cam kap."],
  ["KEMER","Giysiyi belde tutan şerit veya açıklık üzerindeki yay biçimli yapı."],
  ["KILAVUZ","Bir yere veya konuya ilişkin yol gösteren kişi ya da kaynak."],
  ["KİLİT","Bir kapı veya kapağın izinsiz açılmasını önleyen düzenek."],
  ["KLAVYE","Harf ve komut tuşlarıyla bilgisayara veri girilen aygıt."],
  ["KOLONYA","Alkol, su ve hoş kokulu esanslardan oluşan ferahlatıcı sıvı."],
  ["KORİDOR","Odaları birbirine bağlayan uzun ve dar iç geçit."],
  ["KÖPRÜ","İki yakayı bir engelin üzerinden birbirine bağlayan yapı."],
  ["KULAKLIK","Sesi doğrudan kulağa ileten kişisel dinleme aygıtı."],
  ["KUMANDA","Bir aygıtı uzaktan yönetmeye yarayan tuşlu araç."],
  ["KÜRESEL","Bir küre biçiminde olan veya bütün dünyayı ilgilendiren."],
  ["LABİRENT","Çıkışı bulmayı güçleştiren karmaşık geçitler bütünü."],
  ["LAVABO","El ve yüz yıkamak için kullanılan, gideri bulunan tekne."],
  ["LİMAN","Gemilerin yük alıp boşalttığı ve korunaklı biçimde demirlediği yer."],
  ["LOKANTA","Hazırlanmış yemeklerin ücret karşılığında sunulduğu işletme."],
  ["MADALYA","Başarı veya hizmet karşılığında verilen metal nişan."],
  ["MAKARA","İp veya kablonun sarıldığı, ekseni çevresinde dönen silindir."],
  ["MANŞET","Gazetenin en önemli haberini büyük harflerle veren başlık."],
  ["MATKAP","Bir yüzeyde dönen uç yardımıyla delik açan araç."],
  ["MERMER","Parlatıldığında dekorasyon ve yapılarda kullanılan kristalli taş."],
  ["MERCEK","Işığı kırarak görüntüyü büyüten, küçülten veya odaklayan saydam parça."],
  ["MİKROFON","Ses dalgalarını elektrik sinyaline dönüştüren aygıt."],
  ["MİMARİ","Yapıları estetik ve işlevsel ölçülere göre tasarlama sanatı."],
  ["MOBİLYA","Yaşam alanlarında kullanılan taşınabilir masa, koltuk ve benzeri eşya."],
  ["MOTOR","Bir enerji türünü mekanik harekete dönüştüren makine."],
  ["MÜZE","Tarih, bilim veya sanat değeri taşıyan nesnelerin sergilendiği kurum."],
  ["NABIZ","Kalbin atışıyla atardamarlarda hissedilen düzenli hareket."],
  ["NAKIŞ","Kumaş üzerine renkli ipliklerle yapılan süsleme."],
  ["NARENCİYE","Portakal, limon ve mandalina gibi turunçgil ürünlerinin genel adı."],
  ["NOKTALAMA","Yazının anlamını ve duraklarını belirleyen işaretler sistemi."],
  ["OKYANUS","Kıtaları birbirinden ayıran çok geniş ve derin tuzlu su kütlesi."],
  ["OMURGA","İskeletin gövdeyi taşıyan, omurlardan oluşmuş ana bölümü."],
  ["ORKESTRA","Farklı çalgıları birlikte çalan büyük müzik topluluğu."],
  ["OTOGAR","Şehirler arası otobüslerin yolcu indirip bindirdiği terminal."],
  ["OTOPARK","Taşıtların belirli süre bırakılması için ayrılmış alan."],
  ["OYUNCAK","Çocukların eğlenmesi ve öğrenmesi için tasarlanan nesne."],
  ["ÖNLÜK","Giysiyi kirden korumak amacıyla öne takılan örtü."],
  ["ÖRÜMCEK","Sekiz bacaklı, çoğu türü avlanmak için ağ ören canlı."],
  ["PALET","Yüzmede ayağa takılan araç veya ressamın boya karıştırdığı levha."],
  ["PANKART","Bir görüş veya duyurunun büyük yazıyla yer aldığı taşınabilir levha."],
  ["PARAŞÜT","Hava direncinden yararlanarak düşüşü yavaşlatan geniş kumaş düzenek."],
  ["PARKUR","Bir yarış veya antrenman için belirlenmiş engelli güzergâh."],
  ["PASPAS","Zemini silmeye veya ayakkabı tabanını temizlemeye yarayan araç."],
  ["PENCERE","Bir yapıya ışık ve hava girmesini sağlayan camlı açıklık."],
  ["PERGEL","Çember çizmeye ve uzaklık taşımaya yarayan iki kollu araç."],
  ["PERON","Yolcuların trene veya otobüse binmek için beklediği bölüm."],
  ["PİYANO","Tuşlara basıldığında çekiçlerin tellere vurmasıyla ses çıkaran çalgı."],
  ["POSTER","Duvarda sergilenmek üzere hazırlanan büyük basılı görsel."],
  ["PRİZMA","Işığı renklerine ayırabilen veya tabanları eş çok yüzlü cisim."],
  ["PUSULA","Yerkürenin manyetik alanından yararlanarak yön gösteren araç."],
  ["RADYO","Elektromanyetik dalgalarla iletilen ses yayınlarını alan aygıt."],
  ["RAFİNERİ","Ham petrolün kullanılabilir ürünlere ayrıştırıldığı tesis."],
  ["DEMİRYOLU","Trenlerin ilerlemesi için döşenen paralel metal hatların bütünü."],
  ["REÇETE","Hekimin hastaya önerdiği ilaç ve kullanım bilgisini yazdığı belge."],
  ["RÖMORK","Başka bir taşıt tarafından çekilen motorsuz yük aracı."],
  ["RÜZGÂR","Havanın yüksek basınçtan alçak basınca doğru yatay hareketi."],
  ["SAHNE","Gösterinin izleyici karşısında gerçekleştirildiği yükseltilmiş bölüm."],
  ["SANTRAL","Enerji üreten veya iletişim bağlantılarını yöneten merkez."],
  ["SARMAŞIK","Bir yüzeye tutunarak veya dolanarak yükselen bitki."],
  ["SARNIÇ","Yağmur suyu veya içme suyu biriktirmek için yapılan depo."],
  ["SEDYE","Yaralı veya hastayı yatar durumda taşımaya yarayan araç."],
  ["SERA","Bitkilerin denetimli sıcaklıkta yetiştirildiği saydam kapalı yapı."],
  ["SİLİNDİR","İki eş dairesel tabanı ve eğri yan yüzeyi bulunan cisim."],
  ["SİNYAL","Bilgi veya uyarıyı ses, ışık ya da elektrik yoluyla ileten işaret."],
  ["SİREN","Uyarı amacıyla çok güçlü ve kesintili ses çıkaran aygıt."],
  ["SOKET","Bir elektrikli parçanın bağlantı kurmak için takıldığı yuva."],
  ["SPATULA","Karıştırma, sürme veya kazıma için kullanılan yassı uçlu araç."],
  ["STADYUM","Spor karşılaşmalarının geniş seyirci topluluğu önünde yapıldığı alan."],
  ["SEMAVER","Suyu kaynatıp çay demlemek için kullanılan hazneli araç."],
  ["SÜNGER","Sıvıyı içine çekebilen, temizlikte kullanılan gözenekli madde."],
  ["ŞAMANDIRA","Suda yüzerek sınır, yön veya tehlike bildiren işaret."],
  ["ŞELALE","Akarsuyun yüksek bir yerden aşağıya dökülmesiyle oluşan görünüm."],
  ["TABURE","Arkalığı bulunmayan tek kişilik küçük oturak."],
  ["TAKVİM","Günleri, haftaları ve ayları düzenli biçimde gösteren çizelge."],
  ["TAMBUR","Telli bir çalgı veya kablo sarmaya yarayan silindir biçimli parça."],
  ["TARLA","Tarım ürünleri yetiştirmek için işlenen geniş toprak alanı."],
  ["TERMOMETRE","Bir ortamın veya cismin sıcaklığını ölçen araç."],
  ["TERZİ","Giysileri ölçüye göre kesip diken meslek sahibi."],
  ["TESTERE","Sert maddeleri dişli metal ağzıyla kesen araç."],
  ["TİYATRO","Bir olayın oyuncular tarafından sahnede canlandırıldığı sanat dalı."],
  ["TORNAVİDA","Vidaları döndürmeye yarayan saplı el aracı."],
  ["TRAKTÖR","Tarım makinelerini çekmek ve toprağı işlemek için kullanılan taşıt."],
  ["TREN","Raylar üzerinde birbirine bağlı vagonlarla ilerleyen taşıt."],
  ["TURBİN","Akışkanın enerjisini dönme hareketine çeviren makine."],
  ["TÜNEL","Bir engelin altından veya içinden geçirilen kapalı yol."],
  ["UÇURTMA","Rüzgâr yardımıyla ip denetiminde havada tutulan oyuncak."],
  ["UYDU","Bir gezegenin çevresinde dolanan doğal veya insan yapımı cisim."],
  ["VAGON","Trende yolcu veya yük taşımaya yarayan bölümlerden biri."],
  ["VANA","Boru içindeki sıvı veya gaz akışını açıp kapatan düzenek."],
  ["VANTİLATÖR","Dönen kanatlarıyla ortam havasını hareket ettiren aygıt."],
  ["VİYADÜK","Bir yolu vadi veya başka yollar üzerinden geçiren uzun köprü."],
  ["YAĞMURLUK","Yağış sırasında giysileri ıslanmaktan koruyan üstlük."],
  ["YAMAÇ","Bir dağın veya tepenin eğimli yan yüzeyi."],
  ["YELKEN","Rüzgâr gücünü kullanarak tekneyi ilerleten geniş kumaş yüzey."],
  ["MAĞARA","Yer kabuğunda doğal yollarla oluşmuş geniş boşluk."],
  ["YORGAN","Uyurken vücudu sıcak tutmak için kullanılan kalın örtü."],
  ["ZIMPARA","Bir yüzeyi aşındırıp düzeltmeye yarayan pürüzlü malzeme."],
  ["ZİNCİR","Birbirine geçmiş metal halkalardan oluşan uzun bağ."],
  ["ZÜRAFA","Uzun boynu ve benekli gövdesiyle bilinen Afrika memelisi."],
  ["ACIMAK","Birinin üzüntüsü karşısında merhamet duymak."],
  ["AFFETMEK","Yapılan bir yanlışın doğurduğu kırgınlığı sürdürmemek."],
  ["AĞIRLAMAK","Bir konuğu iyi biçimde karşılayıp ihtiyaçlarıyla ilgilenmek."],
  ["ARAŞMAK","Bir şeyi bulmak veya öğrenmek için çevreyi incelemek."],
  ["BAĞIŞLAMAK","Bir kusuru cezalandırmaktan vazgeçmek veya karşılıksız vermek."],
  ["BEKLEMEK","Bir olay gerçekleşene kadar bulunduğu durumda kalmak."],
  ["BİRLEŞMEK","Ayrı parçaların tek bir bütün oluşturması."],
  ["ÇABALAMAK","Bir hedefe ulaşmak için bütün gücüyle uğraşmak."],
  ["ÇEVİRMEK","Bir şeyi kendi ekseni etrafında döndürmek veya başka dile aktarmak."],
  ["DİNLEMEK","Bir sesi anlamak amacıyla dikkatini ona yöneltmek."],
  ["DOĞRULAMAK","Bir bilginin gerçeğe uygun olduğunu kanıtla denetlemek."],
  ["DÜZELTMEK","Yanlış veya bozuk olanı uygun duruma getirmek."],
  ["ERTELEMEK","Yapılması planlanan bir işi daha sonraki zamana bırakmak."],
  ["FISILDAMAK","Başkaları duymayacak kadar alçak sesle konuşmak."],
  ["GÖZLEMEK","Bir değişimi anlamak için dikkatle ve süreklilikle izlemek."],
  ["HATIRLAMAK","Geçmişte öğrenilen veya yaşanan bir şeyi zihne getirmek."],
  ["HESAPLAMAK","Sayıları kullanarak bir niceliğin sonucunu bulmak."],
  ["İNANDIRMAK","Birinin bir düşünceyi doğru kabul etmesini sağlamak."],
  ["KARŞILAMAK","Gelen birini kabul etmek veya bir ihtiyaca yeterli olmak."],
  ["KATLANMAK","Zor bir duruma şikâyet etmeden dayanmak."],
  ["KORUMAK","Birini veya bir şeyi tehlikeden uzak tutmak."],
  ["ÖĞRETMEK","Birinin bilgi ya da beceri kazanmasını sağlamak."],
  ["ÖZLEMEK","Uzakta olan birine veya yere kavuşma isteği duymak."],
  ["CESARETLİ","Olumsuz sonuç ihtimaline rağmen gereken adımı atabilen."],
  ["SAKLANMAK","Görülmemek veya bulunmamak için gizli bir yere çekilmek."],
  ["SAVUNMAK","Bir kişiyi veya görüşü saldırı ve eleştiriye karşı korumak."],
  ["SEVİNMEK","İyi bir gelişme karşısında mutluluk duymak."],
  ["SORGULAMAK","Bir bilginin doğruluğunu nedenleriyle araştırmak."],
  ["TARTIŞMAK","Farklı görüşleri gerekçeleriyle karşılıklı değerlendirmek."],
  ["UZAKLAŞMAK","Bir yerden veya kişiden aradaki mesafeyi artırmak."],
  ["YAKLAŞMAK","Bir hedefle arasındaki mesafeyi azaltmak."],
  ["İMECE","Bir işi köylülerin el birliğiyle ve sırayla yapması geleneği."],
  ["YÜZLEŞMEK","Kaçınılan bir gerçek veya kişiyle doğrudan karşı karşıya gelmek."],
  ["ANLAYIŞLI","Başkalarının durumunu hoşgörüyle değerlendiren."],
  ["ÇALIŞKAN","Görevlerini düzenli ve sürekli emek vererek yapan."],
  ["CÖMERT","Elindekini başkalarıyla paylaşmaktan kaçınmayan."],
  ["DİKKATLİ","Ayrıntıları gözden kaçırmamak için özen gösteren."],
  ["DUYARLI","Çevresindeki sorunları fark edip tepki gösteren."],
  ["ESNEK","Kırılmadan bükülebilen veya koşullara kolay uyum sağlayan."],
  ["HOŞGÖRÜLÜ","Farklı düşünce ve davranışlara anlayış gösterebilen."],
  ["İSTEKLİ","Bir işi yapmaya hevesi ve gönüllülüğü bulunan."],
  ["KARARSIZ","Seçeneklerden birini belirlemekte güçlük çeken."],
  ["MERHAMETLİ","Başkasının acısını azaltmak için yardım etme isteği duyan."],
  ["MÜTEVAZI","Kendi değerini abartmadan sade davranan."],
  ["SABIRSIZ","Beklemekte zorlanan ve sonucu hemen isteyen."],
  ["SAMİMİ","Duygu ve düşüncelerinde içten, yapmacıksız olan."],
  ["ŞAŞKIN","Beklenmedik bir olay karşısında ne yapacağını bilemeyen."],
  ["TEDBİRLİ","Olası tehlikeleri önceden düşünerek önlem alan."],
  ["YENİLİKÇİ","Alışılmış yöntemler yerine yeni fikirleri benimseyen."],
  ["ACELECİ","Bir işi yeterince düşünmeden hızla sonuçlandırmak isteyen."],
  ["BARIŞÇIL","Anlaşmazlıkları şiddet yerine uzlaşmayla çözmek isteyen."],
  ["GİRİŞKEN","Yeni insanlarla iletişim kurmaktan çekinmeyen."],
  ["İYİMSER","Olayların olumlu sonuçlanacağına inanma eğiliminde olan."],
  ["KÖTÜMSER","Olayların olumsuz tarafını görmeye eğilimli olan."],
  ["MANTIKSAL","Düşüncelerini geçerli neden-sonuç ilişkilerine dayandıran."],
  ["ÖZGÜVENLİ","Kendi yeteneklerine ve kararlarına inanan."],
  ["PAYLAŞIMCI","Elindeki bilgi ve imkânı başkalarına açan."],
  ["SORUMSUZ","Üstlendiği işlerin sonucunu önemsemeyen."],
  ["TARAFSIZ","Bir anlaşmazlıkta hiçbir yanı kayırmayan."],
  ["YAPICI","Eleştirirken bile çözüm ve gelişme sağlamayı amaçlayan."],
  ["HAYIRSEVER","İhtiyacı olana karşılık beklemeden destek olan."],
  ["YETENEKLİ","Bir işi öğrenme ve uygulamada doğal başarı gösteren."],
  ["ZEKİ","Yeni bilgiyi çabuk anlayıp sorunlara etkili çözüm bulabilen."],
  ["AKVARYUM","Su canlılarının gözlenip beslendiği saydam kap."],
  ["BATERİ","Birden çok vurmalı çalgının birlikte kullanıldığı müzik takımı."],
  ["DÜRBÜN","Uzaktaki nesneleri daha büyük ve yakın gösteren optik araç."],
  ["FOTOĞRAF","Işığın duyarlı yüzeyde oluşturduğu kalıcı görüntü."],
  ["HEMŞİRE","Hastanın bakımını ve tedavi uygulamalarını yürüten sağlık çalışanı."],
  ["KÜTÜPHANE","Kitap ve bilgi kaynaklarının düzenlenip okura sunulduğu yer."],
  ["MANYETİK","Mıknatısın çekme ve itme özelliğiyle ilgili olan."],
  ["OTOBÜS","Çok sayıda yolcuyu kara yolunda taşıyan büyük motorlu araç."],
  ["ROKET","Tepkili motoruyla atmosferde veya uzayda ilerleyen araç."],
  ["ŞÖVALYE","Orta Çağ Avrupası'nda zırhlı ve atlı savaşçı."],
];

export const moreQuestions: PublicQuestion[] = pairs.map(([answer, clue], index) => ({ answer, clue, origin: "Doğrulanacak", difficulty: (index % 3 === 0 ? "Kolay" : index % 3 === 1 ? "Orta" : "Zor") as PublicQuestion["difficulty"] }));
