import type { PublicQuestion } from "./game";

type Pair = [string, string];
const extra: Record<number, Pair[]> = {
  4: [
    ["ALEV","Yanan bir maddeden yükselen ışıklı ve sıcak dil."],["AYNA","Karşısındakinin görüntüsünü geri veren parlak yüzey."],["BAKI","Gözleri belirli bir noktaya yöneltme biçimi."],["BENT","Suyun akışını kesmek için yapılan engel."],["DOST","İyi ve kötü günde güven duyulan yakın kişi."],["EŞİK","Bir yere girişte aşılan alt sınır."],["EVRE","Bir gelişim sürecinin ayırt edilebilir bölümü."],["HANE","Bir ailenin yaşadığı yer veya sayılardaki basamak."],["ISLA","Kuru bir şeyi suyla nemli duruma getir."],["İZAH","Anlaşılmayan bir konuyu açıklığa kavuşturma."],
    ["KENT","Nüfusu ve yerleşimi köyden büyük yaşam alanı."],["KİRA","Bir şeyi geçici kullanma karşılığında ödenen bedel."],["NEŞE","İçten gelen canlı ve sevinçli ruh hâli."],["ODAK","Işınların veya dikkatin toplandığı merkez."],["ORAN","İki büyüklüğün birbirine göre sayısal ilişkisi."],["OYUK","Bir yüzeyin içine doğru oluşmuş boşluk."],["ÖYKÜ","Yaşanmış veya tasarlanmış olayları anlatan kısa yazı."],["PANO","Duyuru ya da görsellerin sergilendiği düz yüzey."],["PLAN","Bir işi gerçekleştirmeden önce hazırlanan düzen."],["PUSU","Gizlenerek uygun anı bekleme durumu."],
    ["RENK","Işığın gözde oluşturduğu ayırt edici görsel özellik."],["RİSK","Bir kararın olumsuz sonuçlanma ihtimali."],["ŞAKA","Güldürmek amacıyla söylenen ciddi olmayan söz."],["TEMA","Bir eser boyunca işlenen temel düşünce."],["TÖRE","Bir toplulukta kuşaktan kuşağa aktarılan gelenek."],["UYUM","Parçaların birbirini rahatsız etmeden bütün oluşturması."],["ÜRÜN","Emek veya üretim süreci sonunda ortaya çıkan şey."],["VİRA","Denizcilikte bir şeyi yukarı çekme komutu."],["YASA","Toplum düzenini sağlamak için konulan bağlayıcı kural."],["ZEVK","Hoşa giden bir şeyin insanda uyandırdığı duygu."],
  ],
  5: [
    ["AHENK","Seslerin veya parçaların hoş bir bütün oluşturması."],["AŞAMA","Bir sürecin birbirini izleyen bölümlerinden biri."],["BARIŞ","Çatışmanın sona erdiği uzlaşma durumu."],["BİÇİM","Bir varlığın dış görünüşünü belirleyen şekil."],["DEĞER","Bir şeyin önemini ya da karşılığını belirleyen ölçü."],["DENGE","Karşıt güçlerin birbirini aşmadığı kararlı durum."],["DÜZEY","Bir niceliğin ulaştığı derece veya seviye."],["ERDEM","Ahlakça iyi ve doğru sayılan kişilik niteliği."],["EVREN","İçinde tüm gök cisimleri ve maddenin bulunduğu bütün."],["GEREK","Bir şeyin yapılmasını zorunlu kılan ihtiyaç."],
    ["GÜVEN","Birine zarar görmeden dayanabileceğine inanma duygusu."],["HEDEF","Ulaşılmak istenen sonuç veya vurulacak nokta."],["İNANÇ","Bir düşünceyi doğru kabul ederek ona bağlanma."],["KARAR","Seçenekleri değerlendirdikten sonra varılan sonuç."],["KAYGI","Olumsuz bir ihtimal karşısında duyulan tedirginlik."],["KURAL","Bir düzenin işlemesi için uyulması gereken ilke."],["MERAK","Bilinmeyeni öğrenmeye yönelten güçlü istek."],["NEDEN","Bir olayın ortaya çıkmasına yol açan etken."],["SABIR","Güçlüğe veya gecikmeye telaşlanmadan dayanma gücü."],["SAYGI","Birinin değerini kabul ederek ölçülü davranma."],
    ["SEÇİM","Birden çok seçenek arasından birini belirleme."],["SÜREÇ","Bir sonuca doğru birbirini izleyen değişimler bütünü."],["ŞÜPHE","Bir durumun doğruluğundan emin olamama hâli."],["TANIM","Bir kavramın ayırt edici özelliklerini açıklayan söz."],["TEPKİ","Bir etkiye karşı ortaya çıkan davranış veya değişim."],["ÇÖZÜM","Bir sorunu ortadan kaldıran yol veya sonuç."],["DÜZEN","Parçaların belirli bir kurala göre yerleşmiş hâli."],["İLHAM","Yeni bir düşünce veya eser üretmeye yönelten etki."],["ORTAM","Bir canlının veya olayın içinde bulunduğu çevre."],["ZAMAN","Olayların geçmişten geleceğe doğru sıralandığı boyut."],
  ],
  6: [
    ["BAŞARI","Bir işi amaçlanan sonuca ulaştırma durumu."],["EMPATİ","Kendini başkasının yerine koyarak onun duygusunu anlama."],["FARKLI","Benzerleriyle aynı özellikleri taşımayan."],["GERÇEK","Varlığı düşünceden bağımsız olarak bulunan şey."],["GÖZLEM","Bir olayı bilgi edinmek amacıyla dikkatle izleme."],["HAFIZA","Yaşananları saklama ve gerektiğinde hatırlama yetisi."],["İLETİM","Bir bilginin bir noktadan başka bir noktaya aktarılması."],["İLİŞKİ","İki kişi veya olgu arasındaki karşılıklı bağ."],["KARŞIT","Nitelikleri bakımından diğerinin tam tersi olan."],["KİMLİK","Bir kişiyi başkalarından ayıran özellikler bütünü."],
    ["EMANET","Korunmak üzere geçici olarak birine bırakılan şey."],["PAYLAŞ","Elindekini başkalarıyla bölüş veya onlara aktar."],["SİSTEM","Birbiriyle ilişkili parçaların oluşturduğu düzenli bütün."],["ŞEFFAF","Arkasındaki nesnelerin görülmesine izin veren."],["TERCİH","Seçeneklerden birini diğerlerinden üstün tutma."],["TOPLUM","Ortak bir çevrede yaşayan insanların oluşturduğu bütün."],["UZANTI","Bir şeyin ana bölümünden dışarı doğru devam eden parça."],["YETKİN","Bir işi gereken bilgi ve beceriyle yapabilecek durumda."],["BİLİNÇ","Kişinin kendisinin ve çevresinin farkında olma durumu."],["KÜLTÜR","Bir toplumun ürettiği maddi ve manevi değerler bütünü."],
    ["ADALET","Hak ve sorumlulukların ölçülü biçimde dağıtılması."],["ATILIM","Kısa sürede önemli ilerleme sağlamak için yapılan hamle."],["OLANAK","Bir işin gerçekleşmesini sağlayan uygun koşul."],["REDDET","Bir öneriyi veya iddiayı kabul etmediğini bildir."],["İSABET","Bir tahminin veya atışın hedefe uygun düşmesi."],["KANAAT","Bir konu üzerinde düşünülerek varılan kişisel yargı."],["MANTIK","Doğru düşünmenin kurallarını inceleyen yöntem."],["MAKSAT","Bir davranışın gerçekleştirilmesindeki temel amaç."],["ÖLÇMEK","Bir büyüklüğü kabul edilmiş bir birimle karşılaştırmak."],["TASVİR","Bir şeyi özellikleriyle söz veya yazıda canlandırma."],
  ],
  7: [
    ["İRTİBAT","İki kişi veya nokta arasında kurulan haberleşme bağı."],["BİRİKİM","Zaman içinde toplanan bilgi, para veya deneyim."],["ÇÖZÜMCÜ","Sorunları büyütmek yerine çıkış yolu arayan kişi."],["DENEYİM","Bir işi yaşayarak edinilen uygulamalı bilgi."],["DÜŞÜNCE","Zihinde oluşan görüş, fikir veya tasarım."],["YORUMLA","Bir olayı kendi bakış açına göre anlamlandır."],["HABERLİ","Bir durumla ilgili bilgisi bulunan."],["GELENEK","Kuşaktan kuşağa aktarılan yerleşmiş davranış."],["GEREKÇE","Bir yargıyı desteklemek için ileri sürülen neden."],["GİRİŞİM","Bir işi gerçekleştirmek amacıyla başlatılan hareket."],
    ["HAFİFÇE","Ağırlığı veya şiddeti az olacak biçimde."],["GELİŞİM","Bir canlının, düşüncenin veya işin ilerleyerek olgunlaşması."],["AYRINTI","Bir bütün içindeki küçük fakat ayırt edici bölüm."],["BELGELİ","Doğruluğu yazılı bir kanıtla desteklenmiş olan."],["MERKEZİ","Bir sistemin yönetim veya odak noktasına ait."],["NİTELİK","Bir şeyi başkalarından ayıran özellik."],["ÖZGÜNCE","Başkasını taklit etmeden kendine has biçimde."],["PAYDAŞI","Bir işin sonucundan etkilenen veya ona katılan kişi."],["AÇIKLIK","Bir anlatımın kolay anlaşılır ve belirsizlikten uzak olması."],["TASARIM","Bir ürünün biçim ve işlevini önceden kurgulama."],
    ["KÜMESEL","Ortak özellikteki ögelerin oluşturduğu gruba ilişkin."],["ÜRETKEN","Sürekli yeni iş veya düşünce ortaya koyabilen."],["AKSETME","Bir görüntü, ses veya etkinin geri yansıması."],["YARARLI","Bir ihtiyacı karşılayan veya olumlu sonuç sağlayan."],["YÖNELİM","Belirli bir düşünce veya amaca doğru eğilim."],["ZORUNLU","Başka seçeneği bulunmadığı için yapılması gereken."],["BİLDİRİ","Bir konuda bilgi vermek amacıyla hazırlanan kısa açıklama."],["DÖNÜŞÜM","Bir yapının nitelik değiştirerek başka hâle gelmesi."],["ÖZERKÇE","Kararlarını dışarıdan yönetilmeden verecek biçimde."],["TUTARLI","Sözleri ve davranışları kendi içinde çelişmeyen."],
  ],
  8: [
    ["ALGILAMA","Duyulardan gelen bilgiyi zihinde anlamlı hâle getirme."],["ANIMSAMA","Geçmişte öğrenilen bir bilgiyi yeniden hatıra getirme."],["BELİRMEK","Daha önce görünmezken fark edilir duruma gelmek."],["BÜTÜNLÜK","Parçaların eksiksiz ve uyumlu bir yapı oluşturması."],["CANLILIK","Enerjik, hareketli ve yaşam dolu olma durumu."],["DAVRANIŞ","Bir canlının bir durum karşısında gösterdiği tepki."],["DERİNLİK","Bir yüzeyden aşağıya veya içeriye olan uzaklık."],["GELİŞMEK","Zamanla daha ileri ve olgun bir duruma ulaşmak."],["BİÇİMSEL","İçerikten çok dış yapı ve kuruluşa ilişkin olan."],["KARŞILIK","Verilen veya yapılan bir şeye cevap olarak sunulan şey."],
    ["KURGUSAL","Gerçek olaylardan değil hayal gücünden doğan."],["MANTIKLI","Akla uygun ve kendi içinde çelişki taşımayan."],["PAYLAŞIM","Bilgi veya imkânı başkalarının kullanımına açma."],["TEPKİSEL","Önceden planlamak yerine gelişmeye göre davranan."],["TOPLUMCU","Bireysel çıkardan önce ortak yararı gözeten."],["UYGULAMA","Bir düşünceyi veya yöntemi gerçekte hayata geçirme."],["YARATICI","Daha önce bulunmayan özgün fikirler üretebilen."],["YÖNETİCİ","Bir kurumun işlerini düzenleyip yönlendiren kişi."],["DÜŞÜNSEL","Zihinsel etkinlik ve fikirlerle ilgili olan."],["GEÇİŞKEN","Bir etkinin bir ögeden diğerine aktarılabildiği."],
    ["GÖSTERGE","Bir durumun varlığını veya değişimini belli eden işaret."],["İŞLEVSEL","Görünüşten çok kullanım amacına uygun olan."],["KATILMAK","Bir topluluğun veya etkinliğin parçası olmak."],["ÖĞRENMEK","Bilgi ve beceriyi çalışma veya deneyimle edinmek."],["PLANLAMA","Bir işi başlamadan önce aşamalarıyla düzenleme."],["YORUMLAR","Bir konu hakkında kişisel değerlendirmeler yapar."],["DUYGUSAL","Kararlarında hislerin etkisi ağır basan."],["BİLİMSEL","Deney, gözlem ve kanıta dayanan."],["BAŞARILI","Belirlenen amaca istenen düzeyde ulaşmış olan."],["ÇEKİNGEN","Kendini öne çıkarmaktan kaçınan, utangaç davranan."],
  ],
  9: [
    ["BAŞLANGIÇ","Bir olayın veya sürecin ilk noktası."],["DAYANIKLI","Zorlu koşullara bozulmadan uzun süre direnebilen."],["DÜRÜSTLÜK","Söz ve davranışlarda gerçeğe bağlı kalma niteliği."],["FARKLILIK","Benzer görünenleri birbirinden ayıran özellik."],["HASSASLIK","Küçük değişimleri bile fark edip tepki verebilme."],["KATILIMCI","Bir etkinlikte yalnız izlemeyip etkin rol alan kişi."],["NESNELLİK","Kişisel duyguları değerlendirmeye karıştırmama ilkesi."],["ZORLAYICI","Sonuca ulaşmak için olağandan fazla çaba gerektiren."],["ARAŞTIRMA","Bir soruya güvenilir cevap bulmak için yürütülen çalışma."],["DEĞERLEME","Bir şeyin önemini belirlemek için yapılan inceleme."],
    ["HATIRLAMA","Geçmişte yaşananı yeniden zihne getirme."],["İNCELEMEK","Bir konuyu ayrıntılarına ayırarak dikkatle araştırmak."],["GÖSTERİCİ","Bir özelliği veya sonucu açıkça ortaya koyan."],["SÜRDÜRMEK","Başlamış bir işi kesintiye uğratmadan devam ettirmek."],["TANIMLAMA","Bir kavramın sınırlarını ve özelliklerini belirtme."],["UYGULAMAK","Bir kuralı veya düşünceyi davranışa dönüştürmek."],["YORUMLAMA","Bir olayın anlamını kişisel bakışla açıklama."],["ZENGİNLİK","Maddi veya manevi kaynakların bol olması."],["YENİLENME","Eskiyen bir yapının tazelenerek yeniden işler duruma gelmesi."],["BAĞDAŞMAK","İki düşünce veya durumun birbiriyle uyum göstermesi."],
    ["YANSITICI","Işığı, sesi veya bir etkiyi geldiği yöne geri gönderen."],["ÇALIŞMALI","Bir sonuca ulaşmak için emek vermesi gereken."],["DÜZENLEME","Dağınık ögeleri belirli bir kurala göre yerleştirme."],["GELENEKÇİ","Yerleşmiş alışkanlıkların korunmasını savunan."],["GÖRECELİK","Bilginin koşullara ve bakış açısına bağlı olduğunu savunan görüş."],["İKİRCİKLİ","Karar verirken iki seçenek arasında gidip gelen."],["KARŞITLIK","Birbirine zıt özelliklerin aynı bağlamda bulunması."],["ÖZELLİKLİ","Benzerlerinden ayıran belirgin nitelikleri bulunan."],["SEÇENEKLİ","Birden fazla tercih imkânı sunan."],["TASARIMCI","Bir ürünün biçim ve işlevini kurgulayan kişi."],
  ],
  10: [
    ["BİLGİSAYAR","Verileri komutlara göre işleyip sonuç üreten elektronik aygıt."],["AYDINLATMA","Bir ortamı ışıkla görünür duruma getirme işi."],["ÜNİVERSİTE","Yüksek düzeyde eğitim ve araştırma yapılan kurum."],["ELEKTRONİK","Elektronların davranışına dayalı aygıtlarla ilgili alan."],["ALTERNATİF","Bir seçeneğin yerine değerlendirilebilecek başka yol."],["PERFORMANS","Bir kişinin veya sistemin ortaya koyduğu başarı düzeyi."],["TEKNOLOJİK","Bilimsel bilginin uygulamalı araçlarına ilişkin."],["PSİKOLOJİK","Zihinsel süreçler ve insan davranışlarıyla ilgili."],["GELENEKSEL","Uzun zamandır sürdürülen alışkanlıklara dayanan."],["TELEVİZYON","Görüntü ve sesi uzaktan alıp ekrana aktaran aygıt."],
    ["DEĞİŞİKLİK","Bir durumun önceki hâlinden farklılaşması."],["DEMOKRATİK","Kararlara halkın katılımını ve eşitliği gözeten."],["POTANSİYEL","Henüz ortaya çıkmamış fakat gerçekleşme gücü bulunan."],["İSTİHBARAT","Karar vermek amacıyla gizli veya açık kaynaklardan toplanan bilgi."],["SORUŞTURMA","Bir olayın gerçeklerini ortaya çıkarmak için yapılan resmî inceleme."],["GÜNCELLEME","Bir bilgiyi veya yazılımı en yeni duruma getirme."],["KARŞILIKLI","İki tarafın birbirine aynı yönde etkide bulunduğu."],["ETKİLEYİCİ","Gören veya dinleyende güçlü bir iz bırakan."],["OLAĞANÜSTÜ","Alışılmış sınırların belirgin biçimde dışında kalan."],["MOTİVASYON","Bir kişiyi hedefe doğru harekete geçiren iç veya dış güç."],
    ["UYUŞTURUCU","Algıyı değiştirip bağımlılık oluşturabilen madde."],["ENGELLEMEK","Bir olayın gerçekleşmesine veya sürmesine mâni olmak."],["ALIŞKANLIK","Tekrarlandıkça düşünmeden yapılır hâle gelen davranış."],["BELİRLEMEK","Bir şeyin sınırlarını veya niteliğini kesinleştirmek."],["BİLİNMEYEN","Hakkında yeterli bilgi bulunmayan şey."],["DEĞİŞTİRME","Bir şeyi önceki hâlinden farklı duruma getirme."],["BAĞLANTILI","Aralarında anlamlı bir ilişki veya bağ bulunan."],["GÖSTERGESİ","Bir durumun varlığını anlamaya yarayan işareti."],["KULLANIŞLI","Bir ihtiyacı kolay ve etkili biçimde karşılayan."],["KAÇINILMAZ","Koşullar gereği gerçekleşmesi önlenemeyen."],
  ],
};

export const extraQuestions: PublicQuestion[] = Object.entries(extra).flatMap(([length, pairs]) => pairs.map(([answer, clue], index) => ({ answer, clue, origin: "Doğrulanacak", difficulty: (Number(length) <= 5 && index < 10 ? "Kolay" : index >= 20 ? "Zor" : "Orta") as PublicQuestion["difficulty"] })));
